export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const DELETE_CART = "DELETE_CART";
export const ADD_SHIPPING_TO_CART = "ADD_SHIPPING_TO_CART";
export const DELETE_CART_ITEMS = "DELETE_CART_ITEMS";
