export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";

export const GET_ORDER_FOR_ADMIN_REQUEST = "GET_ORDER_FOR_ADMIN_REQUEST";
export const GET_ORDER_FOR_ADMIN_SUCCESS = "GET_ORDER_FOR_ADMIN_SUCCESS";
export const GET_ORDER_FOR_ADMIN_FAIL = "GET_ORDER_FOR_ADMIN_FAIL";

export const GET_MY_ORDERS_REQUEST = "GET_MY_ORDERS_REQUEST";
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS";
export const GET_MY_ORDERS_FAIL = "GET_MY_ORDERS_FAIL";

export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL";
