export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST";
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";
export const USER_DETAIL_FAIL = "USER_DETAIL_FAIL";

export const USER_DETAIL_FOR_ADMIN_REQUEST = "USER_DETAIL_FOR_ADMIN_REQUEST";
export const USER_DETAIL_FOR_ADMIN_SUCCESS = "USER_DETAIL_FOR_ADMIN_SUCCESS";
export const USER_DETAIL_FOR_ADMIN_FAIL = "USER_DETAIL_FOR_ADMIN_FAIL";
export const USER_DETAIL_FOR_ADMIN_RESET = "USER_DETAIL_FOR_ADMIN_RESET";
